#!/usr/bin/env node
/**
 * Snapshots the live API's home page + footer content into
 * src/data/landingContent.ts so the static fallback used by Landing.tsx
 * and GlobalFooter is never more than one build behind reality.
 *
 * Behavior policy:
 *  - On success: rewrites src/data/landingContent.ts.
 *  - On API unreachable: prints a loud warning, leaves the existing
 *    landingContent.ts in place, exits 0 so the build still succeeds.
 *  - On API reachable but data malformed/incomplete: exits 1 to fail
 *    the build. Better to block a deploy than ship a broken fallback.
 *
 * Configure with SNAPSHOT_API_URL (default: http://localhost:4000).
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TARGET = path.resolve(__dirname, "..", "src", "data", "landingContent.ts");
const API = process.env.SNAPSHOT_API_URL ?? "http://localhost:4000";

const EXPECTED_SECTION_TYPES = [
  "hero",
  "philosophy",
  "overview",
  "mission-vision",
  "values",
  "impact-model",
  "services",
  "geography",
  "social-impact",
  "leadership",
  "future-vision",
];

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${url} returned HTTP ${res.status}`);
  }
  return res.json();
}

function transformHero(content) {
  return {
    label: content.badge,
    title: content.headlineBlack,
    titleEm: content.headlineBlue,
    subText: content.description,
    primaryCta:
      typeof content.ctas?.[0] === "object"
        ? content.ctas[0].label
        : content.ctas?.[0],
    ghostCta:
      typeof content.ctas?.[1] === "object"
        ? content.ctas[1].label
        : content.ctas?.[1],
    stats: content.stats,
  };
}

function transformServices(content) {
  return {
    label: content.label,
    title: content.title,
    items: content.items ?? content.cards,
    footer: {
      title: content.footerTitle,
      text: content.footerText,
    },
  };
}

function buildContent(homePage, footer) {
  // Index sections by type for O(1) lookup
  const byType = Object.fromEntries(
    (homePage.sections ?? []).map((s) => [s.type, s.content])
  );

  // Validation: every expected section must be present
  const missing = EXPECTED_SECTION_TYPES.filter((t) => !byType[t]);
  if (missing.length > 0) {
    throw new Error(
      `API home page is missing sections: ${missing.join(", ")}. ` +
        `Check the backend seed.`
    );
  }

  return {
    hero: transformHero(byType["hero"]),
    philosophy: byType["philosophy"],
    overview: byType["overview"],
    missionVision: byType["mission-vision"],
    values: byType["values"],
    impactModel: byType["impact-model"],
    services: transformServices(byType["services"]),
    geography: byType["geography"],
    socialImpact: byType["social-impact"],
    leadership: byType["leadership"],
    futureVision: byType["future-vision"],
    contact: footer.contact,
    footer: footer.footer,
  };
}

function render(content, sourceUrl, timestamp) {
  const banner =
    `// AUTO-GENERATED by scripts/snapshot-content.mjs — DO NOT EDIT BY HAND.\n` +
    `// Source: ${sourceUrl}\n` +
    `// Generated: ${timestamp}\n` +
    `// To refresh, run: npm run snapshot:content\n\n`;
  return banner + `export const landingContent = ${JSON.stringify(content, null, 2)};\n`;
}

async function main() {
  console.log(`[snapshot] fetching content from ${API} ...`);

  let homePage, footer;
  try {
    [homePage, footer] = await Promise.all([
      fetchJson(`${API}/api/pages/home`),
      fetchJson(`${API}/api/footer`),
    ]);
  } catch (err) {
    console.warn(
      `[snapshot] ⚠️  could not reach API (${err.message}). ` +
        `Keeping existing landingContent.ts unchanged.`
    );
    process.exit(0);
  }

  const content = buildContent(homePage, footer);
  const timestamp = new Date().toISOString();
  const output = render(content, API, timestamp);

  await fs.writeFile(TARGET, output, "utf8");
  console.log(`[snapshot] ✓ wrote ${path.relative(process.cwd(), TARGET)}`);
}

main().catch((err) => {
  console.error(`[snapshot] ❌ ${err.message}`);
  console.error(`[snapshot]    Refusing to overwrite landingContent.ts with broken data.`);
  process.exit(1);
});